"""
可下载词典包：GRE、考研、医学、科研、商务等专业词汇。

每个 pack 定义一组单词列表。查询时从 ecdict.db 提取释义。
用户启用 pack 后，这些词会被纳入标注范围（即使在其英语等级之外）。
"""

import json
import logging
import sqlite3
from pathlib import Path
from typing import Any

from settings import get_settings

logger = logging.getLogger(__name__)

# ── 词典包定义 ──────────────────────────────

# SVG icon fragments (16×16, stroke style, currentColor)
_SVG = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">'
_ICONS: dict[str, str] = {
    # GRE: open book
    "gre": f'{_SVG}<path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"/><path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"/></svg>',
    # postgrad: graduation cap
    "postgrad": f'{_SVG}<path d="M22 10v6M2 10l10-5 10 5-10 5z"/><path d="M6 12v5c0 1.1 2.7 3 6 3s6-1.9 6-3v-5"/></svg>',
    # medical: heart pulse
    "medical": f'{_SVG}<path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z"/><path d="M3.22 12H9.5l.5-1 2 4.5 2-7 1.5 3.5h5.27"/></svg>',
    # scientific: flask / beaker
    "scientific": f'{_SVG}<path d="M9 3h6"/><path d="M10 3v7.4a2 2 0 0 1-.6 1.4L4 17.2a2 2 0 0 0-.6 1.4V20a1 1 0 0 0 1 1h15.2a1 1 0 0 0 1-1v-1.4a2 2 0 0 0-.6-1.4l-5.4-5.4a2 2 0 0 1-.6-1.4V3"/></svg>',
    # business: briefcase
    "business": f'{_SVG}<rect width="20" height="14" x="2" y="7" rx="2" ry="2"/><path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"/></svg>',
    # tech: terminal / code
    "tech": f'{_SVG}<polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/></svg>',
    # legal: scale / balance
    "legal": f'{_SVG}<line x1="12" y1="3" x2="12" y2="21"/><path d="M5 12H2l3.5-7L9 12H5z"/><path d="M19 12h-3l3.5-7L23 12h-4z"/><line x1="8" y1="21" x2="16" y2="21"/></svg>',
    # toefl: globe
    "toefl": f'{_SVG}<circle cx="12" cy="12" r="10"/><line x1="2" y1="12" x2="22" y2="12"/><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></svg>',
}

PACKS: dict[str, dict[str, Any]] = {
    "gre": {
        "id": "gre",
        "name": "GRE 核心词汇",
        "description": "GRE 考试高频词汇，涵盖学术写作和阅读常见难词",
        "icon": _ICONS["gre"],
        "word_count": 0,  # 运行时计算
        "category": "考试",
    },
    "postgrad": {
        "id": "postgrad",
        "name": "考研英语",
        "description": "考研英语高频词汇，侧重阅读理解和翻译",
        "icon": _ICONS["postgrad"],
        "word_count": 0,
        "category": "考试",
    },
    "medical": {
        "id": "medical",
        "name": "医学词汇",
        "description": "常见医学术语、解剖学、药理学、临床词汇",
        "icon": _ICONS["medical"],
        "word_count": 0,
        "category": "专业",
    },
    "scientific": {
        "id": "scientific",
        "name": "科研学术",
        "description": "学术论文高频词汇，涵盖研究方法、统计、发表等",
        "icon": _ICONS["scientific"],
        "word_count": 0,
        "category": "专业",
    },
    "business": {
        "id": "business",
        "name": "商务英语",
        "description": "商务会议、谈判、金融、管理常用词汇",
        "icon": _ICONS["business"],
        "word_count": 0,
        "category": "专业",
    },
    "tech": {
        "id": "tech",
        "name": "科技互联网",
        "description": "编程、人工智能、产品、互联网行业术语",
        "icon": _ICONS["tech"],
        "word_count": 0,
        "category": "专业",
    },
    "legal": {
        "id": "legal",
        "name": "法律词汇",
        "description": "法律文书、合同、诉讼常见术语",
        "icon": _ICONS["legal"],
        "word_count": 0,
        "category": "专业",
    },
    "toefl": {
        "id": "toefl",
        "name": "托福核心",
        "description": "托福考试高频词汇，侧重学术听力和阅读",
        "icon": _ICONS["toefl"],
        "word_count": 0,
        "category": "考试",
    },
}

# ── GRE 核心词汇 ──
_GRE_WORDS = {
    "aberrant", "abeyance", "abjure", "abnegate", "abscond", "abstemious",
    "accolade", "acerbic", "acrimonious", "acumen", "admonish", "adroit",
    "adulterate", "advocate", "aesthetic", "affable", "aggrandize", "alacrity",
    "alchemy", "alleviate", "amalgamate", "ambiguous", "ambivalent", "ameliorate",
    "amenable", "anachronism", "analogous", "anarchy", "anomalous", "antagonism",
    "antediluvian", "antipathy", "apathetic", "appease", "apprise", "arbitrary",
    "arcane", "archaic", "arduous", "articulate", "ascetic", "assiduous",
    "assuage", "astute", "atrophy", "audacious", "auspicious", "austere",
    "avarice", "banal", "belie", "belligerent", "benevolent", "boorish",
    "bombastic", "bolster", "bucolic", "burgeon", "cacophony", "cajole",
    "capricious", "castigate", "catalyst", "caustic", "censure", "chicanery",
    "circumscribe", "clandestine", "coalesce", "cogent", "commensurate",
    "compendium", "complaisant", "conciliatory", "condone", "conflagration",
    "connoisseur", "contrite", "conundrum", "convoluted", "copious",
    "corroborate", "cosmopolitan", "craven", "credulous", "curtail",
    "cynical", "dearth", "debacle", "decorum", "deference", "defunct",
    "deleterious", "delineate", "denigrate", "denounce", "deride",
    "derivative", "desiccate", "despondent", "desultory", "diatribe",
    "dichotomy", "didactic", "diffident", "digress", "dilatory",
    "dilettante", "dirge", "disabuse", "discerning", "discordant",
    "discrete", "disingenuous", "disparage", "disparate", "disseminate",
    "dissonance", "distend", "divergent", "docile", "dogmatic",
    "dormant", "draconian", "dubious", "duplicity", "ebullient",
    "eclectic", "edify", "efface", "effervescent", "efficacy",
    "egregious", "elegy", "elucidate", "emaciate", "embellish",
    "emollient", "empirical", "emulate", "endemic", "enervate",
    "engender", "enigma", "ennui", "ephemeral", "epitome",
    "equanimity", "equivocal", "erudite", "eschew", "esoteric",
    "euphemism", "evanescent", "exacerbate", "exculpate", "exemplary",
    "exigent", "exonerate", "expatiate", "expedient", "expunge",
    "extant", "extemporaneous", "extol", "extraneous", "facetious",
    "facilitate", "fallacious", "fastidious", "fatuous", "fawning",
    "fecund", "felicitous", "fervent", "filibuster", "flag",
    "flagrant", "florid", "foment", "forestall", "fortuitous",
    "fractious", "frugal", "furtive", "gainsay", "galvanize",
    "garrulous", "germane", "glib", "grandiloquent", "gregarious",
    "gullible", "hackneyed", "halcyon", "harangue", "harbinger",
    "hedonist", "hegemony", "heresy", "heterogeneous", "hubris",
    "iconoclast", "idiosyncratic", "ignominious", "immutable",
    "impartial", "impecunious", "impede", "impervious", "implacable",
    "implicit", "importune", "impugn", "inchoate", "incipient",
    "incongruity", "incorporate", "incorrigible", "incredulous",
    "indeterminate", "indifferent", "indigent", "indolent", "ineluctable",
    "inexorable", "ingenuous", "inherent", "innocuous", "inscrutable",
    "insipid", "insolent", "intractable", "intransigent", "intrepid",
    "inundate", "inure", "invective", "inveterate", "irascible",
    "itinerant", "judicious", "juxtapose", "laconic", "lambaste",
    "lament", "languid", "largesse", "laud", "laudable",
    "lethargic", "levity", "litigant", "loquacious", "lucid",
    "luminous", "magnanimous", "malfeasance", "malign", "malleable",
    "mandate", "martinet", "maudlin", "maverick", "mendacious",
    "mercurial", "meticulous", "milieu", "misanthrope", "mitigate",
    "mollify", "morose", "mundane", "munificent", "myopic",
    "nadir", "nascent", "nebulous", "nefarious", "neophyte",
    "nonchalant", "nondescript", "notorious", "obdurate", "obfuscate",
    "oblique", "obsequious", "obstinate", "obtuse", "obviate",
    "occlude", "onerous", "opaque", "opportunist", "opprobrium",
    "ornate", "orthodox", "oscillate", "ostentatious", "pacific",
    "palatable", "palliate", "panacea", "paradigm", "paragon",
    "parochial", "parsimonious", "partisan", "pathological", "paucity",
    "pedantic", "penchant", "penurious", "perennial", "perfidious",
    "perfunctory", "peripheral", "permeate", "pernicious", "perpetuate",
    "pertinacious", "pervasive", "petulant", "philanthropic", "phlegmatic",
    "placate", "platitude", "plausible", "plethora", "polemical",
    "pragmatic", "precarious", "precipitate", "preclude", "precocious",
    "presumptuous", "prevaricate", "pristine", "probity", "proclivity",
    "prodigal", "prodigious", "profligate", "profuse", "prohibitive",
    "proliferate", "prolific", "propensity", "propitiate", "prosaic",
    "proscribe", "protean", "provident", "provincial", "prudent",
    "pugnacious", "punctilious", "punitive", "putative", "quagmire",
    "querulous", "quiescent", "quotidian", "rancorous", "rapacious",
    "rarefy", "raucous", "recalcitrant", "recant", "recondite",
    "redoubtable", "refute", "relegate", "remonstrate", "replete",
    "reprehensible", "reprobate", "repudiate", "rescind", "reticent",
    "reverent", "rhetoric", "ribald", "rife", "robust",
    "rudimentary", "ruminate", "rustic", "sagacious", "salient",
    "salubrious", "sanction", "sanguine", "satiate", "saturate",
    "scrupulous", "sedulous", "self-serving", "sobriety", "solicitous",
    "soporific", "specious", "sporadic", "spurious", "stolid",
    "strident", "stymie", "subjugate", "substantiate", "succinct",
    "superfluous", "supplant", "supposition", "surreptitious", "sycophant",
    "tacit", "taciturn", "tangential", "temerity", "temperate",
    "tenacious", "terse", "timorous", "torpid", "tortuous",
    "tractable", "transgression", "transient", "tremulous", "trenchant",
    "truculent", "tumultuous", "turgid", "turpitude", "ubiquitous",
    "umbrage", "unctuous", "undermine", "underscore", "unequivocal",
    "untenable", "upbraid", "urbane", "vacillate", "vapid",
    "variegated", "vehement", "venal", "venerate", "veracious",
    "verbose", "vestige", "viable", "vigilant", "vilify",
    "vindicate", "virtuoso", "virulent", "viscous", "vitiate",
    "vitriolic", "vociferous", "volatile", "voracious", "warranted",
    "wary", "welter", "whimsical", "wistful", "zealous",
}

# ── 考研英语 ──
_POSTGRAD_WORDS = {
    "abandon", "abide", "abolish", "absurd", "abstract", "abundant",
    "accommodate", "accomplish", "accumulate", "acquaint", "adequate",
    "adhere", "adjacent", "advocate", "aggravate", "aggregate",
    "agitate", "allocate", "allege", "allude", "alternate",
    "ambiguous", "amend", "analogy", "apparatus", "apparent",
    "apprehend", "apt", "arbitrary", "ascend", "aspire",
    "assault", "assert", "assess", "assimilate", "attribute",
    "authentic", "authorize", "autonomous", "avail", "avert",
    "bias", "breach", "bureaucracy", "catalyst", "cater",
    "chronic", "cite", "cognition", "coherent", "coincide",
    "collaborate", "collision", "commence", "commodity", "compatible",
    "compelling", "compensate", "competent", "complement", "comply",
    "comprehensive", "compulsory", "conceive", "confine", "conform",
    "confront", "conscientious", "consensus", "consequent", "conserve",
    "consolidate", "constitute", "constrain", "contemplate", "contempt",
    "contradiction", "controversy", "conversion", "convey", "coordinate",
    "correlate", "correspondence", "corrode", "counsel", "counterpart",
    "credible", "culminate", "cumulative", "currency", "curriculum",
    "debris", "decline", "dedicate", "default", "deficiency",
    "degradation", "deliberate", "demographic", "denounce", "deplete",
    "deprive", "derive", "designate", "detach", "deteriorate",
    "deviate", "devise", "dictate", "differentiate", "diffuse",
    "dilemma", "diminish", "discard", "disclose", "discourse",
    "discrimination", "dismiss", "dispatch", "disperse", "displace",
    "disposition", "dispute", "disrupt", "dissolve", "distort",
    "diversity", "doctrine", "domain", "domestic", "dominant",
    "doom", "drastic", "drought", "duration", "dwell",
    "elaborate", "elicit", "eligible", "eliminate", "embark",
    "embrace", "emerge", "emit", "empirical", "encompass",
    "encounter", "endorse", "enforce", "enlighten", "entail",
    "entity", "envision", "episode", "equate", "eradicate",
    "erode", "essence", "evaluate", "evoke", "evolve",
    "exceed", "exclude", "exempt", "exert", "exotic",
    "explicit", "exploit", "exposition", "extent", "extract",
    "fabricate", "facilitate", "feasible", "flaw", "fluctuate",
    "foremost", "formidable", "forthcoming", "foster", "fragment",
    "friction", "fuse", "futile", "gender", "genuine",
    "glacier", "glossary", "gloomy", "grant", "graphic",
    "gravity", "hamper", "harness", "hazard", "heritage",
    "hierarchy", "highlight", "hinder", "hormone", "hostage",
    "hover", "hypothesis", "identical", "ideology", "illuminate",
    "immense", "immune", "imperative", "implicate", "implicit",
    "impose", "impulse", "inaugurate", "incentive", "incidence",
    "incline", "incorporate", "incur", "indefinite", "indispensable",
    "induce", "infer", "inflation", "infrastructure", "ingenious",
    "inherent", "initiate", "innovative", "insight", "inspect",
    "integral", "integrate", "integrity", "intellectual", "intensify",
    "intervene", "intimate", "intricate", "intrinsic", "intuition",
    "invade", "invoke", "irony", "isolate", "jeopardize",
    "jurisdiction", "justify", "kinetic", "laden", "landmark",
    "launch", "legitimate", "levy", "liberal", "likelihood",
    "literal", "litigation", "lofty", "manifest", "manipulate",
    "marginal", "mechanism", "mediate", "merchandise", "merit",
    "metabolism", "methodology", "militant", "minimize", "momentum",
    "monopoly", "mortgage", "motivate", "mounting", "municipal",
    "navigate", "negotiate", "neutral", "nonetheless", "norm",
    "notable", "notify", "notorious", "notwithstanding", "nucleus",
    "nurture", "objective", "oblige", "obscure", "obsolete",
    "offset", "ongoing", "opt", "orient", "orthodox",
    "outbreak", "outweigh", "overlap", "override", "overwhelming",
    "paradox", "parallel", "parameter", "passionate", "patent",
    "patrol", "peer", "penalty", "penetrate", "perceive",
    "perpetual", "persistent", "perspective", "pervasive", "petition",
    "phase", "phenomenon", "plausible", "pledge", "plunge",
    "portfolio", "portray", "pose", "postpone", "potent",
    "precedent", "precipitate", "preclude", "predominantly", "preliminary",
    "premise", "premium", "prerequisite", "prescribe", "prestige",
    "presumably", "prevail", "primitive", "privilege", "probe",
    "proclaim", "profound", "prohibit", "proliferate", "prominent",
    "prone", "propagate", "propel", "prospect", "protocol",
    "provoke", "prudent", "purge", "pursuit", "qualitative",
    "quota", "radiate", "radical", "ratify", "rational",
    "realm", "reconcile", "recur", "referendum", "reform",
    "reinforce", "relentless", "relevant", "reluctant", "remedy",
    "render", "repeal", "replicate", "repress", "reproach",
    "resort", "restrain", "resume", "retain", "retrieve",
    "revelation", "revenue", "reverse", "revive", "rhetoric",
    "rigid", "ritual", "robust", "safeguard", "sanction",
    "scatter", "scenario", "scrutiny", "secular", "segment",
    "sheer", "simultaneous", "skeptical", "solidarity", "sovereign",
    "specify", "spectrum", "speculate", "spouse", "stagger",
    "stake", "stationary", "statute", "stereotype", "stimulate",
    "stipulate", "strategic", "strive", "subordinate", "subsequent",
    "subsidy", "substantial", "substitute", "subtle", "succession",
    "sue", "summit", "superb", "supplement", "suppress",
    "surge", "surplus", "surveillance", "sustain", "sworn",
    "symmetry", "syndrome", "tackle", "tangible", "tariff",
    "tempt", "tentative", "terminate", "terrain", "thesis",
    "threshold", "thrive", "toll", "toxic", "trait",
    "transaction", "transcend", "transit", "transparent", "trauma",
    "trigger", "triumph", "trivial", "tumble", "turbulent",
    "undergo", "underlie", "undertake", "unprecedented", "upgrade",
    "uphold", "utilize", "valid", "vanish", "venture",
    "verdict", "verify", "versatile", "vest", "viable",
    "vigorous", "violate", "virtual", "vow", "vulnerable",
    "warrant", "weave", "welfare", "whereby", "widespread",
    "withhold", "withstand", "workforce", "yield",
}

# ── 医学词汇 ──
_MEDICAL_WORDS = {
    "abdomen", "abscess", "acute", "adenoma", "adhesion", "adrenaline",
    "adverse", "allergy", "amnesia", "amputation", "analgesic", "anemia",
    "anesthesia", "angina", "anterior", "antibiotic", "antibody", "antigen",
    "aorta", "appendix", "arrhythmia", "artery", "arthritis", "aseptic",
    "asthma", "atrophy", "autopsy", "bacteria", "benign", "biopsy",
    "bladder", "blood", "bone", "bronchitis", "capsule", "cardiac",
    "carcinoma", "cardiovascular", "cartilage", "catheter", "cerebral",
    "cervical", "chemotherapy", "chronic", "cirrhosis", "clinical",
    "coagulate", "coma", "complication", "concussion", "congenital",
    "cortex", "cranial", "cyst", "deficiency", "degenerate",
    "dehydration", "dementia", "diagnosis", "dialysis", "diastolic",
    "diffuse", "dissect", "dosage", "dysfunction", "edema",
    "electrode", "embolism", "embryo", "endocrine", "enzyme",
    "epidemic", "epilepsy", "epithelial", "etiology", "excision",
    "femoral", "fibrous", "fistula", "fracture", "gastric",
    "gestation", "glucose", "graft", "hemorrhage", "hepatic",
    "hernia", "hormone", "hypertension", "hypothermia", "immunity",
    "implant", "incision", "infarction", "inflammation", "infusion",
    "insulin", "intubation", "ischemia", "kidney", "larynx",
    "lateral", "lesion", "leukemia", "ligament", "lumbar",
    "lymph", "malignant", "membrane", "meningitis", "metabolism",
    "metastasis", "microbe", "migraine", "mortality", "mucous",
    "nausea", "necrosis", "neonatal", "neurology", "nucleus",
    "obstetric", "oncology", "optic", "orthopedic", "osteoporosis",
    "palpitation", "pancreas", "paralysis", "pathogen", "pathology",
    "pediatric", "pelvis", "penicillin", "peripheral", "pharynx",
    "plasma", "pneumonia", "posterior", "prenatal", "prognosis",
    "prosthesis", "protein", "psychiatric", "pulmonary", "radiology",
    "receptor", "rectum", "renal", "respiratory", "resuscitate",
    "retina", "rheumatism", "rupture", "sclerosis", "sedative",
    "seizure", "sepsis", "serum", "spinal", "splint",
    "stenosis", "sterile", "stimulant", "suture", "symptom",
    "syndrome", "systemic", "tendon", "therapeutic", "thoracic",
    "thrombosis", "thyroid", "tissue", "toxin", "trachea",
    "transfusion", "transplant", "trauma", "tumor", "ulcer",
    "ultrasound", "uterus", "vaccination", "vascular", "ventricle",
    "vertebra", "viral", "visceral",
}

# ── 科研学术词汇 ──
_SCIENTIFIC_WORDS = {
    "abstract", "algorithm", "analysis", "anomaly", "apparatus",
    "appendix", "assertion", "assumption", "attenuation", "benchmark",
    "bias", "calibrate", "catalyst", "causality", "coefficient",
    "cognitive", "cohort", "collaborate", "compile", "component",
    "computation", "concurrent", "confound", "conjecture", "consensus",
    "constraint", "construct", "contingency", "converge", "correlation",
    "criterion", "dataset", "decompose", "deduce", "demographic",
    "denote", "dependent", "derivative", "deterministic", "deviate",
    "dichotomy", "differential", "dimensionality", "discrete", "disseminate",
    "diverge", "domain", "efficacy", "empirical", "enumerate",
    "equate", "equilibrium", "elucidate", "emergent", "entropy",
    "epoch", "estimate", "evaluate", "exogenous", "exponential",
    "extrapolate", "feasibility", "formulate", "framework", "frequency",
    "generalize", "gradient", "granularity", "heuristic", "homogeneous",
    "hypothesis", "implication", "incidence", "incorporate", "index",
    "infer", "inherent", "initialize", "innovate", "instantiate",
    "interpolate", "iteration", "latent", "leverage", "likelihood",
    "linear", "longitudinal", "magnitude", "manifest", "matrix",
    "mechanism", "methodology", "metric", "mitigate", "modality",
    "modular", "monotonic", "multifaceted", "multivariate", "nontrivial",
    "normalize", "null", "objective", "observe", "optimal",
    "outlier", "paradigm", "parameter", "partial", "partition",
    "peer-review", "perturbation", "phenomenon", "posterior", "pragmatic",
    "precursor", "predominant", "preliminary", "prevalence", "probability",
    "propagate", "proposition", "protocol", "proxy", "qualitative",
    "quantify", "random", "rationale", "recurrence", "redundancy",
    "regression", "replicate", "reproducible", "residual", "robust",
    "salient", "scalar", "scalable", "sensitivity", "sequential",
    "significance", "simulate", "specification", "specimen", "spectrum",
    "stochastic", "stratify", "subsequent", "substantiate", "sufficient",
    "surrogate", "synthesis", "systematic", "taxonomy", "temporal",
    "theoretical", "threshold", "topology", "trajectory", "trivial",
    "truncate", "ubiquitous", "underlying", "unilateral", "validate",
    "variable", "variance", "versatile", "volatile",
}

# ── 商务英语 ──
_BUSINESS_WORDS = {
    "acquisition", "affiliate", "agenda", "allocate", "amortize",
    "annuity", "appraisal", "arbitrage", "asset", "audit",
    "bail", "balance", "bankrupt", "benchmark", "beneficiary",
    "bid", "bond", "brokerage", "budget", "bureaucracy",
    "capital", "cashflow", "charter", "clause", "collateral",
    "commission", "commodity", "compliance", "conglomerate", "consortium",
    "contingency", "contractor", "convene", "copyright", "corporate",
    "creditor", "currency", "custodian", "deadline", "debenture",
    "debit", "deficit", "delegate", "depreciation", "derivative",
    "diligence", "discount", "dividend", "downturn", "embargo",
    "endowment", "enterprise", "equity", "escrow", "expenditure",
    "fiduciary", "fiscal", "forecast", "franchise", "freight",
    "fulfillment", "governance", "gross", "guarantee", "hedge",
    "holdings", "incentive", "incorporate", "indemnity", "inflation",
    "insolvency", "interest", "inventory", "invoice", "jurisdiction",
    "lease", "leverage", "liability", "liquidate", "litigation",
    "logistics", "margin", "markup", "maturity", "mediate",
    "merger", "mortgage", "negotiate", "nominal", "obligation",
    "offshore", "operating", "outsource", "overhead", "patent",
    "payable", "payroll", "portfolio", "premium", "principal",
    "procurement", "profit", "prospectus", "provision", "quota",
    "ratify", "receivable", "reconcile", "remittance", "restructure",
    "revenue", "royalty", "securities", "shareholder", "solvent",
    "stakeholder", "subsidiary", "surplus", "tariff", "tender",
    "trademark", "transaction", "turnover", "underwrite", "valuation",
    "venture", "volatility", "wholesale", "yield",
}

# ── 科技互联网 ──
_TECH_WORDS = {
    "algorithm", "analytics", "annotation", "application", "architecture",
    "asynchronous", "authenticate", "autonomous", "backend", "bandwidth",
    "binary", "blockchain", "boolean", "bootstrap", "buffer",
    "cache", "callback", "ciphertext", "cluster", "codebase",
    "compile", "component", "concurrency", "configuration", "container",
    "cryptography", "daemon", "dashboard", "database", "debug",
    "decrypt", "deploy", "deprecate", "deserialization", "deterministic",
    "docker", "ecosystem", "embed", "emulate", "encrypt",
    "endpoint", "enumeration", "epoch", "ethernet", "executable",
    "firmware", "framework", "frontend", "gateway", "generative",
    "granularity", "hash", "heuristic", "hyperparameter", "idempotent",
    "immutable", "inference", "initialize", "instance", "integrate",
    "interface", "iterate", "kernel", "kubernetes", "latency",
    "lifecycle", "logging", "middleware", "migrate", "microservice",
    "modular", "multithreading", "namespace", "neural", "normalize",
    "optimization", "orchestrate", "overfitting", "parameter", "parse",
    "partition", "payload", "pipeline", "pixel", "plugin",
    "polymorphism", "preprocessing", "primitive", "protocol", "provision",
    "proxy", "query", "queue", "recursive", "refactor",
    "regression", "render", "repository", "resilient", "runtime",
    "sandbox", "scaffold", "scalable", "schema", "semantic",
    "serialization", "serverless", "singleton", "snippet", "socket",
    "sprint", "stack", "stateless", "streaming", "synchronous",
    "template", "tensor", "throughput", "timestamp", "tokenize",
    "topology", "transpile", "troubleshoot", "truncate", "tuple",
    "underfitting", "upstream", "validate", "vector", "verbose",
    "version", "virtualization", "webhook", "widget",
}

# ── 法律词汇 ──
_LEGAL_WORDS = {
    "acquit", "adjudicate", "affidavit", "allegation", "amend",
    "appeal", "appellant", "arbitrate", "arraign", "bail",
    "bench", "binding", "breach", "brief", "burden",
    "bylaw", "case", "caveat", "citation", "claimant",
    "clause", "coercion", "compliance", "consent", "contempt",
    "convict", "counsel", "counterclaim", "covenant", "custody",
    "decree", "defendant", "deposition", "disclosure", "discretion",
    "dismiss", "disposition", "dissolution", "doctrine", "due",
    "enact", "enforce", "equity", "estoppel", "eviction",
    "evidence", "exempt", "exonerate", "extradite", "felony",
    "fiduciary", "filing", "forfeiture", "fraud", "habeas",
    "hearing", "immunity", "impeach", "indict", "indictment",
    "injunction", "jurisdiction", "jurisprudence", "larceny", "lawsuit",
    "legislation", "liability", "lien", "litigation", "magistrate",
    "mandate", "mediation", "misdemeanor", "mitigate", "moot",
    "negligence", "oath", "objection", "obligor", "ordinance",
    "parole", "perjury", "petition", "plaintiff", "plea",
    "precedent", "probation", "prosecution", "provision", "punitive",
    "ratify", "recourse", "restitution", "retainer", "sanction",
    "settlement", "slander", "sovereign", "statute", "stipulate",
    "subpoena", "sue", "summons", "testimony", "tort",
    "tribunal", "verdict", "violation", "waive", "warrant",
    "witness",
}

# ── 托福核心 ──
_TOEFL_WORDS = {
    "abandon", "absorb", "abstract", "accelerate", "accessible",
    "accommodate", "accumulate", "adapt", "adequate", "adjacent",
    "advocate", "aggregate", "allocate", "alter", "ambiguous",
    "analogous", "apparatus", "appropriate", "approximate", "arbitrary",
    "attribute", "authentic", "automate", "bias", "bureaucracy",
    "capacity", "catastrophe", "chronic", "circulate", "circumstance",
    "collapse", "commence", "commodity", "compatible", "compensate",
    "compile", "complement", "comprehensive", "compulsory", "conceive",
    "configuration", "confront", "consecutive", "consent", "consequent",
    "considerable", "consolidate", "constitute", "constrain", "contempt",
    "context", "controversy", "convene", "convert", "coordinate",
    "correspond", "criterion", "crucial", "cumulative", "currency",
    "decade", "decline", "deduce", "deficit", "definite",
    "demonstrate", "denote", "deplete", "deprive", "designate",
    "detect", "deteriorate", "devise", "differentiate", "diminish",
    "discard", "disclose", "discourse", "discrete", "discriminate",
    "displace", "dispose", "distinct", "distribute", "diverse",
    "document", "domestic", "dominant", "drain", "duration",
    "elaborate", "elicit", "eligible", "eliminate", "embrace",
    "emerge", "emit", "emphasis", "encompass", "encounter",
    "endorse", "enhance", "enormous", "entity", "equate",
    "equivalent", "erode", "estate", "evaluate", "evident",
    "evolve", "exceed", "exclude", "execute", "exempt",
    "exhibit", "expand", "explicit", "exploit", "extract",
    "facilitate", "feasible", "fluctuate", "foundation", "fragment",
    "function", "fundamental", "generate", "globe", "grant",
    "guarantee", "hierarchy", "hypothesis", "identical", "ideology",
    "illustrate", "immense", "implement", "implicit", "impose",
    "impulse", "incentive", "incidence", "incline", "incorporate",
    "indicate", "induce", "inevitable", "infrastructure", "inherent",
    "initiate", "innovate", "insight", "inspect", "instance",
    "integrate", "integrity", "intellectual", "intense", "interact",
    "intermediate", "interval", "intervene", "intrinsic", "invoke",
    "isolate", "justify", "launch", "layer", "legislate",
    "legitimate", "levy", "liberal", "link", "locate",
    "maintain", "manipulate", "marginal", "mature", "mechanism",
    "migrate", "minimize", "modify", "monitor", "motivate",
    "mutual", "negate", "neutral", "nonetheless", "norm",
    "notion", "nuclear", "objective", "obtain", "obvious",
    "occupy", "offset", "ongoing", "operate", "orient",
    "outcome", "output", "overlap", "panel", "participate",
    "perceive", "persist", "perspective", "phenomenon", "plausible",
    "portion", "pose", "potential", "precede", "precise",
    "predominant", "preliminary", "presume", "prevail", "principal",
    "proceed", "prohibit", "project", "promote", "proportion",
    "prospect", "protocol", "province", "provoke", "pursue",
    "radical", "range", "ratio", "rational", "react",
    "refine", "regime", "register", "regulate", "reinforce",
    "relevant", "reluctant", "rely", "render", "reside",
    "resolve", "resource", "respond", "restore", "restrain",
    "retain", "reveal", "revenue", "reverse", "revise",
    "rigid", "route", "scenario", "scheme", "scope",
    "sector", "secure", "segment", "significant", "simulate",
    "sole", "source", "specify", "sphere", "stable",
    "statistic", "status", "strategy", "subsequent", "subsidy",
    "substantial", "substitute", "sufficient", "supplement", "survey",
    "sustain", "symbol", "target", "technique", "temporary",
    "terminate", "theme", "thereby", "thesis", "trace",
    "tradition", "transfer", "transform", "transmit", "transport",
    "trigger", "ultimate", "undergo", "underlie", "undertake",
    "uniform", "unique", "utilize", "valid", "variable",
    "vary", "vehicle", "verify", "version", "via",
    "violate", "virtual", "visible", "volume", "voluntary",
    "widespread",
}

_PACK_WORDS: dict[str, set[str]] = {
    "gre": _GRE_WORDS,
    "postgrad": _POSTGRAD_WORDS,
    "medical": _MEDICAL_WORDS,
    "scientific": _SCIENTIFIC_WORDS,
    "business": _BUSINESS_WORDS,
    "tech": _TECH_WORDS,
    "legal": _LEGAL_WORDS,
    "toefl": _TOEFL_WORDS,
}

# 计算实际词数
for pack_id, words in _PACK_WORDS.items():
    if pack_id in PACKS:
        PACKS[pack_id]["word_count"] = len(words)


def list_packs() -> list[dict]:
    """返回所有可用词典包的元信息列表。"""
    return list(PACKS.values())


def get_pack_words(pack_id: str) -> set[str] | None:
    """返回指定词典包的单词集合。"""
    return _PACK_WORDS.get(pack_id)


def get_combined_pack_words(pack_ids: list[str]) -> set[str]:
    """返回多个词典包合并后的单词集合。"""
    combined: set[str] = set()
    for pid in pack_ids:
        words = _PACK_WORDS.get(pid)
        if words:
            combined |= words
    return combined
