"""
分级词汇表：根据用户英语水平过滤已知词汇

等级体系（累进制，高级包含低级全部词汇）：
  kindergarten  幼儿园  ~150 词  基础功能词、颜色、数字、家庭
  elementary    小学    ~600 词  日常生活高频词
  middle_school 初中    ~1600 词 初中课标词汇
  high_school   高中    ~3500 词 高中课标 / CET-4
  college       大学    ~5500 词 CET-6
  ielts         雅思    ~8000 词 IELTS 7+ / 高级学术
  professional  专业    ~11000词 只标注极专业术语
"""

from __future__ import annotations

import logging
from functools import lru_cache

logger = logging.getLogger(__name__)

# 合法等级名（有序，从低到高）
LEVEL_ORDER: list[str] = [
    "kindergarten",
    "elementary",
    "middle_school",
    "high_school",
    "college",
    "ielts",
    "professional",
]

LEVEL_LABELS: dict[str, str] = {
    "kindergarten":  "幼儿园",
    "elementary":    "小学",
    "middle_school": "初中",
    "high_school":   "高中",
    "college":       "大学",
    "ielts":         "雅思",
    "professional":  "专业",
}

# ──────────────────────────────────────────────
# 每级新增词汇（增量，不含之前等级）
# ──────────────────────────────────────────────

_KINDERGARTEN = {
    # 功能词 / 代词
    "the","a","an","i","you","he","she","it","we","they","me","my","your",
    "his","her","its","our","their","this","that","is","am","are","was","were",
    "be","do","does","did","have","has","had","can","will","not","no","yes",
    "and","or","but","if","so","of","in","on","at","to","for","with","from",
    "up","down","out","off","over","under","by","about",
    # 数字
    "one","two","three","four","five","six","seven","eight","nine","ten",
    # 颜色
    "red","blue","green","yellow","white","black","pink","orange","brown","purple",
    # 家庭
    "mom","dad","mother","father","sister","brother","baby","family",
    # 身体
    "head","eye","ear","nose","mouth","hand","foot","leg","arm","hair",
    # 动物
    "dog","cat","fish","bird","pig","cow","horse","duck","chicken","rabbit",
    # 食物 / 饮料
    "water","milk","egg","rice","bread","cake","apple","banana","food","drink",
    # 日常
    "hello","hi","bye","thank","please","sorry","good","bad","big","small",
    "hot","cold","new","old","happy","sad","boy","girl","man","woman",
    "house","home","school","book","pen","bag","door","bed","box","toy",
    "sun","moon","star","tree","flower","rain","day","night","go","come",
    "see","eat","run","play","say","like","want","get","put","sit",
    "stand","open","close","help","look","give","take","make","know",
}

_ELEMENTARY = {
    # 常见动词
    "ask","answer","begin","bring","buy","call","carry","catch","change",
    "clean","climb","cook","copy","count","cover","cry","cut","dance","draw",
    "dream","drive","drop","enjoy","enter","fall","feel","fill","find","finish",
    "fly","follow","forget","grow","guess","happen","hate","hear","hold","hope",
    "hurry","join","jump","keep","kick","kill","laugh","lay","lead","learn",
    "leave","let","lie","lift","listen","live","lose","love","mean","meet",
    "miss","move","must","need","pack","pass","pay","pick","point","pull",
    "push","read","remember","return","ride","ring","rise","save","sell",
    "send","share","show","shut","sing","sleep","smell","smile","speak",
    "spell","spend","start","stay","stop","study","swim","talk","teach",
    "tell","think","throw","touch","try","turn","understand","use","visit",
    "wait","wake","walk","wash","watch","wear","win","wish","work","worry",
    "write",
    # 常见名词
    "afternoon","age","air","animal","arm","aunt","back","ball","beach",
    "bell","bike","birthday","boat","body","bottle","breakfast","bridge","bus",
    "car","card","chair","child","children","church","circle","city","class",
    "classroom","clock","clothes","cloud","coat","color","corner","country",
    "cup","daughter","desk","dinner","doctor","dress","ear","earth","east",
    "evening","exam","face","farm","field","film","fire","floor","friend",
    "fruit","game","garden","gift","glass","gold","grass","ground","group",
    "hair","hat","heart","hill","holiday","hospital","hotel","hour","idea",
    "island","job","key","king","kitchen","knife","lake","land","letter",
    "library","life","light","line","lion","list","lunch","map","market",
    "math","meal","meat","meeting","message","mile","mind","minute","mirror",
    "money","month","morning","mountain","movie","museum","music","name",
    "neck","news","newspaper","north","nose","note","number","nurse","ocean",
    "office","page","pair","paper","parent","park","party","path","people",
    "pet","phone","photo","picture","piece","place","plane","plant","pool",
    "price","prize","problem","queen","question","radio","rest","river",
    "road","room","rule","sand","season","seat","shirt","shoe","shop",
    "side","sight","sign","silver","sky","snow","son","song","south",
    "space","sport","spring","stage","step","stone","store","story","street",
    "student","sugar","summer","supper","table","teacher","team","test",
    "ticket","time","town","train","trip","trouble","uncle","village","voice",
    "wall","war","way","weather","week","weekend","west","wife","wind",
    "window","winter","woman","wood","word","world","yard","year","zoo",
    # 常见形容词
    "able","afraid","alone","angry","beautiful","best","better","blind",
    "born","brave","bright","busy","cheap","clear","clever","close","cool",
    "dark","dead","dear","deep","different","difficult","dirty","dry","each",
    "easy","empty","enough","every","evil","extra","fair","famous","far",
    "fast","fat","few","final","fine","first","foreign","free","fresh",
    "full","funny","glad","great","half","hard","healthy","heavy","high",
    "honest","huge","hungry","ill","important","inside","interesting","kind",
    "last","late","lazy","left","less","little","long","loud","lovely","low",
    "lucky","main","many","more","much","natural","near","next","nice","north",
    "only","outside","own","perfect","poor","possible","pretty","proud","quiet",
    "ready","real","rich","right","round","safe","same","second","short",
    "sick","silly","simple","slow","soft","some","south","special","strange",
    "strong","sure","sweet","tall","terrible","thick","thin","third","thirsty",
    "tired","top","true","ugly","warm","weak","wet","whole","wide","wild",
    "wise","wonderful","wrong","young",
    # 常见副词
    "again","ago","almost","already","also","always","away","back","early",
    "else","enough","ever","fast","finally","hard","here","how","however",
    "just","later","maybe","more","most","much","never","now","often","once",
    "only","perhaps","quite","really","so","sometimes","soon","still","then",
    "there","today","together","tomorrow","tonight","too","usually","very",
    "well","yet",
    # 功能词补充
    "all","another","any","anything","because","before","behind","below",
    "between","both","other","should","these","those","though","through",
    "until","upon","what","when","where","which","while","who","whose","why",
    "may","might","shall","per","via",
}

_MIDDLE_SCHOOL = {
    # 动词（初中课标提升）
    "accept","achieve","act","add","admit","advise","afford","agree","allow",
    "appear","apply","argue","arrive","avoid","beat","become","believe",
    "belong","borrow","break","breathe","build","burn","cancel","cause",
    "celebrate","check","choose","collect","compare","complete","connect",
    "consider","contain","continue","control","correct","cost","create",
    "cross","damage","deal","decide","deliver","depend","describe","design",
    "destroy","develop","die","dig","disappear","discover","discuss","divide",
    "doubt","dry","earn","encourage","escape","examine","exchange","excite",
    "excuse","exercise","exist","expect","experience","explain","express",
    "fail","fear","feed","fetch","fight","fit","fix","flow","force","form",
    "gain","hang","heat","hide","hit","hunt","hurry","imagine","improve",
    "include","increase","influence","inform","insist","introduce","invent",
    "invite","involve","judge","land","last","lend","limit","manage","mark",
    "match","matter","measure","mention","mix","nod","notice","obey","offer",
    "operate","order","organize","owe","own","pack","perform","permit",
    "plan","pour","practice","prefer","prepare","present","prevent","produce",
    "promise","protect","prove","provide","punish","raise","reach","realize",
    "receive","record","reduce","refuse","regret","relate","relax","remain",
    "remind","remove","repair","repeat","replace","reply","report","require",
    "research","respect","result","review","satisfy","search","seem","separate",
    "serve","set","settle","shape","shout","solve","sort","spread","steal",
    "stick","succeed","suffer","suggest","supply","support","suppose",
    "surprise","taste","test","tie","train","translate","treat","trust",
    "value","warn","waste","weigh","welcome","wonder",
    # 名词（初中课标提升）
    "ability","accident","action","activity","address","advantage",
    "advertisement","advice","agreement","amount","anger","apartment",
    "appearance","area","army","art","article","attention","audience",
    "award","background","bank","base","basic","basket","bath","battle",
    "behavior","bit","blood","board","bone","border","boss","bottom",
    "brain","breast","breath","brush","budget","bug","camp","cancer",
    "cap","capital","captain","career","case","cash","cause","center",
    "central","century","chain","challenge","champion","chance","channel",
    "chapter","character","chart","chest","choice","coach","coal","coast",
    "code","college","comfort","command","comment","community",
    "communication","company","competition","complaint","computer",
    "condition","confidence","conflict","connection","conversation","copy",
    "courage","course","court","crash","crime","crowd","culture","customer",
    "cycle","danger","data","date","deal","death","debate","decision",
    "degree","department","desert","detail","development","diet","direction",
    "director","discovery","discussion","disease","distance","district",
    "doubt","draft","duty","economy","edge","education","effect","effort",
    "election","emergency","emotion","energy","engine","environment",
    "equipment","escape","essay","event","evidence","examination","example",
    "exchange","excitement","exercise","experiment","expert","expression",
    "fact","factor","fan","fashion","fat","fear","feature","fee","feeling",
    "festival","fiction","figure","flag","flight","focus","force",
    "form","fortune","freedom","fun","function","future","gap","gas",
    "generation","goal","grade","growth","guard","guide","habit","hall",
    "health","height","hero","history","hole","honey","human","humor",
    "ice","image","imagination","impact","income","increase","independence",
    "industry","influence","information","interest","internet","interview",
    "iron","item","journey","joy","judge","justice","knowledge","labor",
    "lack","lady","law","layer","leader","league","leather","length",
    "lesson","level","lid","limit","link","literature","location","lock",
    "loss","luck","machine","magazine","manager","manner","material",
    "meaning","media","medicine","member","memory","metal","method",
    "middle","million","model","moment","mood","movement","murder","muscle",
    "mystery","nation","nature","neighbor","network","noise","object",
    "occasion","operation","opinion","opportunity","option","origin","owner",
    "pain","painting","passage","pattern","peace","percent","performance",
    "period","personality","phrase","physics","pilot","plastic","platform",
    "pleasure","poem","poet","poetry","point","poison","policy","politics",
    "pollution","population","position","possibility","post","pot","powder",
    "power","pressure","pride","prince","princess","principle","process",
    "production","product","profession","professor","profit","program",
    "progress","project","promise","property","public","purpose","quality",
    "race","reality","reason","record","region","relation","relationship",
    "religion","report","republic","requirement","research","resource",
    "respect","response","responsibility","result","revolution","reward",
    "risk","rock","role","root","rope","row","safety","salary","sample",
    "scale","scene","schedule","science","score","screen","secret",
    "section","security","seed","self","sense","sentence","series",
    "service","session","shadow","shape","shelf","shell","shock","shore",
    "signal","silence","situation","size","skill","skin","slave","smoke",
    "society","software","soil","soldier","solution","soul","source",
    "speed","spirit","spread","square","staff","standard","state",
    "statement","station","status","steel","stick","stock","stomach",
    "storm","strategy","strength","stress","strike","string","structure",
    "stuff","style","subject","success","surface","symbol","system","tail",
    "talent","tank","taste","tax","technique","technology","temperature",
    "term","text","theory","thought","thousand","threat","title","toe",
    "tone","tool","tooth","topic","total","touch","tour","tower","track",
    "trade","tradition","traffic","training","transport","trash","travel",
    "treasure","treatment","trend","trial","trick","trust","truth","type",
    "unit","valley","variety","vehicle","version","victim","victory",
    "view","violence","volume","wealth","weapon","weight","wheel","wild",
    "wing","wonder","worker","youth",
    # 形容词 / 副词补充
    "actual","ancient","available","average","basic","bitter","blank","blind",
    "brief","calm","central","certain","chemical","chief","civil","classic",
    "comfortable","common","complex","concerned","confident","confused",
    "conscious","constant","cool","creative","critical","cruel","cultural",
    "curious","current","daily","dangerous","definite","delicious",
    "democratic","desperate","direct","double","due","eager","effective",
    "electric","electronic","entire","environmental","equal","essential",
    "exact","excellent","exciting","expensive","extreme","false","familiar",
    "fantastic","fat","favorite","female","fierce","flat","former","frequent",
    "gentle","global","golden","grand","gray","guilty","narrow","negative",
    "nervous","normal","obvious","official","opposite","ordinary","original",
    "particular","patient","personal","physical","plain","pleasant","plenty",
    "political","popular","positive","powerful","precious","present",
    "previous","primary","private","professional","proper","public","pure",
    "rare","raw","regular","religious","responsible","rough","royal",
    "scientific","secret","senior","sensitive","separate","serious","severe",
    "sharp","shy","significant","silent","similar","slight","smart","smooth",
    "social","solid","specific","standard","steady","steep","strict",
    "stupid","sudden","super","terrible","tight","tiny","total","tough",
    "traditional","typical","unique","unknown","unusual","upper","useful",
    "usual","valuable","vast","violent","visible","visual","warm","wooden",
    "worth","absolutely","actually","apparently","basically","briefly",
    "carefully","certainly","clearly","completely","constantly","currently",
    "deeply","definitely","directly","easily","effectively","entirely",
    "especially","essentially","eventually","exactly","extremely","fairly",
    "fortunately","frequently","generally","gently","gradually","hardly",
    "heavily","highly","immediately","indeed","largely","likely","merely",
    "mostly","naturally","nearly","necessarily","normally","obviously",
    "particularly","perfectly","personally","possibly","potentially",
    "precisely","previously","primarily","probably","properly","purely",
    "quickly","quietly","rapidly","rarely","rather","recently","relatively",
    "seriously","sharply","significantly","simply","slightly","slowly",
    "softly","somehow","somewhat","specifically","strongly","successfully",
    "suddenly","surely","therefore","thoroughly","typically","ultimately",
    "unfortunately","usually","widely",
}

_HIGH_SCHOOL = {
    # 动词（高中 / CET-4 提升）
    "abandon","absorb","abuse","accompany","accumulate","accuse","adapt",
    "address","adjust","administer","adopt","advocate","alter","amaze",
    "amuse","analyze","announce","anticipate","apologize","appeal",
    "appreciate","approach","approve","arise","arrange","assess","assign",
    "assist","associate","assume","assure","attach","attempt","attract",
    "ban","bargain","bear","bend","bet","bind","blame","blast","bless",
    "block","blow","boast","bomb","bond","boost","bore","bother","bounce",
    "bow","broadcast","burden","burst","bury","calculate","campaign",
    "capture","cast","cease","challenge","charge","chase","cheat","cheer",
    "circulate","cite","clarify","classify","cling","collapse","combat",
    "combine","comfort","commit","communicate","compensate","compete",
    "compile","complain","compose","concentrate","conclude","conduct",
    "confess","confine","confirm","confront","confuse","conquer",
    "constitute","construct","consult","consume","convince","cooperate",
    "cope","correspond","count","crash","crawl","crush","cure","dare",
    "dawn","debate","declare","decline","decorate","decrease","defeat",
    "defend","define","delay","delight","demand","demonstrate","deny",
    "depart","deposit","depress","derive","deserve","desire","detect",
    "determine","devote","differ","diminish","disappoint","discipline",
    "dismiss","display","distinguish","distribute","disturb","dominate",
    "donate","drag","drown","dump","ease","edit","elect","eliminate",
    "embrace","emerge","emit","employ","enable","encounter","endure",
    "engage","enhance","ensure","equip","erect","establish","estimate",
    "evaluate","evolve","exceed","exclude","execute","exhibit","expand",
    "exploit","explore","export","expose","extend","extract","fade",
    "fascinate","flash","flee","float","flood","forbid","forecast",
    "forgive","found","freeze","frighten","fulfill","fund","furnish",
    "generate","grab","grasp","greet","grip","guarantee","handle",
    "harvest","heal","hesitate","highlight","hire","honor","host","hunt",
    "identify","illustrate","imply","import","impose","impress","indicate",
    "inherit","initial","inject","injure","inquire","insert","inspect",
    "install","instruct","insure","integrate","intend","interpret",
    "interrupt","investigate","irritate","isolate","justify","label",
    "launch","lean","leap","liberate","load","locate","lodge","maintain",
    "manufacture","march","master","maximize","merit","migrate","minimize",
    "modify","monitor","mount","multiply","negotiate","neglect","nominate",
    "oblige","observe","obtain","occupy","oppose","opt","overcome",
    "overlook","overtake","owe","participate","perceive","persist",
    "persuade","pile","pitch","plead","pledge","plunge","polish","pose",
    "possess","postpone","pray","precede","predict","preserve","pretend",
    "proceed","process","project","promote","prompt","pronounce","propose",
    "protest","pursue","qualify","quit","quote","rage","react","reckon",
    "recommend","recover","recruit","reflect","reform","register","reject",
    "release","rely","remark","rescue","resign","resist","resolve",
    "restore","restrict","retain","retire","retreat","reveal","reverse",
    "revise","revolt","rob","rotate","ruin","rush","sacrifice","scan",
    "scatter","secure","seize","shift","shrink","sigh","simulate","sink",
    "sketch","skip","slip","smash","snap","soak","soar","spark","spin",
    "split","sponsor","squeeze","stain","stare","starve","stem","stimulate",
    "stir","strain","strengthen","stretch","strip","stroke","struggle",
    "submit","substitute","sustain","sweep","swell","switch","tackle",
    "target","tear","tend","terrify","testify","thrive","tighten","toss",
    "trace","transform","transmit","trap","trigger","trim","undergo",
    "undertake","unfold","update","upgrade","urge","utilize","vanish",
    "venture","verify","violate","volunteer","vote","wander","weave",
    "whisper","withdraw","witness","wrap","yield",
    # 名词（高中 / CET-4 提升）
    "abortion","absence","academy","access","accommodation","acquisition",
    "administration","adolescent","agenda","agriculture","aid","aircraft",
    "alarm","alcohol","alliance","altitude","amendment","analyst","anchor",
    "anniversary","anxiety","apparatus","appetite","appliance","architecture",
    "arena","aspect","assault","assembly","asset","assignment","assumption",
    "atmosphere","authority","autobiography","awareness","ban","barrier",
    "battery","behalf","benefit","bias","biology","blade","blessing","bloom",
    "bond","boom","boundary","bow","brake","breed","broadcast","browser",
    "burden","cabin","cabinet","campaign","candidate","capacity","carbon",
    "cargo","carpet","catalog","cattle","cave","cell","ceremony","charity",
    "chemistry","circuit","circumstance","civilian","civilization","cliff",
    "clinic","clothing","cluster","coalition","colleague","colony","column",
    "comedy","commerce","commission","commitment","committee","commodity",
    "companion","comparison","compensation","complexity","component",
    "composition","concept","concrete","consensus","consequence",
    "conservation","consideration","conspiracy","constitution","consultant",
    "consumption","content","context","contract","contribution",
    "controversy","convention","corporation","counsel","coverage","craft",
    "creation","creature","crew","crisis","criterion","criticism","crop",
    "curiosity","currency","curriculum","custom","dairy","database","dawn",
    "deadline","deficit","democracy","demon","departure","depression",
    "deputy","destiny","device","diagnosis","dialogue","dignity","dimension",
    "diplomat","disability","discipline","discrimination","disorder",
    "disposal","distinction","diversity","doctrine","documentary","domain",
    "donation","dose","draft","drama","dwelling","dynamics","earnings",
    "echo","ecology","economics","ecosystem","edition","efficiency",
    "element","elite","emission","emperor","empire","encounter","ending",
    "enthusiasm","entity","entry","epidemic","episode","era","erosion",
    "essence","estate","establishment","ethics","evolution","exception",
    "execution","executive","expedition","expense","exploitation",
    "explosion","exposure","extension","extent","facility","faculty",
    "fairy","fantasy","fate","fax","feast","fiber","fiction","flame",
    "flesh","flexibility","flour","formula","fossil","foundation",
    "framework","franchise","freight","frequency","friction","frontier",
    "frost","fuel","fury","gallery","garbage","gear","gesture","ghost",
    "glory","gospel","governance","grab","grain","gravity","grief",
    "grocery","guerrilla","habitat","hardware","harmony","headline",
    "headquarters","heritage","horizon","horror","hostage","household",
    "humanity","hurricane","hydrogen","hypothesis","ideology","illusion",
    "immigration","immunity","implement","implication","import","impulse",
    "incident","index","indication","infrastructure","ingredient",
    "initiative","innovation","input","inquiry","insight","inspection",
    "installation","instance","institution","instrument","insurance",
    "integrity","intellect","intelligence","intensity","interaction",
    "interior","intervention","invasion","inventory","investigation",
    "investor","irrigation","isolation","journal","jurisdiction","jury",
    "label","landscape","lane","layout","lecture","legacy","legend",
    "legislation","leisure","liability","liberty","lieutenant","lifetime",
    "literacy","livestock","lobby","logic","luxury","machinery","mainland",
    "maintenance","majority","mandate","margin","marine","marketplace",
    "mask","mate","mechanism","memorial","mercy","merger","mess",
    "metabolism","metaphor","methodology","ministry","minority","miracle",
    "missile","mission","mixture","mode","molecule","momentum","monitor",
    "monopoly","monument","mortgage","motive","mud","myth","narrative",
    "navigation","necessity","negotiation","nightmare","nomination","norm",
    "notion","nucleus","nutrition","obligation","obstacle","offspring",
    "opponent","orbit","orchestra","organ","organism","orientation",
    "outbreak","outcome","outline","output","oversight","oxygen","pace",
    "palace","panel","parade","parallel","parish","participant",
    "partnership","passport","patch","patrol","peak","penalty","pension",
    "perception","perspective","petition","phenomenon","philosophy",
    "physician","pioneer","pipeline","pitch","plea","plot","plug","pole",
    "portfolio","portion","portrait","pose","possession","poster",
    "potential","poverty","premium","prescription","presidency","preview",
    "prey","priority","privilege","probe","procedure","profession",
    "profile","projection","promotion","proportion","proposal",
    "proposition","prosecution","prospect","prosperity","protocol",
    "province","provision","publicity","pump","pursuit","puzzle",
    "quota","radiation","radical","rally","ratio","realm","recession",
    "recommendation","reconstruction","referendum","reflection","refuge",
    "regime","regulation","rehabilitation","reign","reinforcement",
    "relevance","remedy","renovation","representation","reproduction",
    "reputation","reservation","residence","resolution","resort",
    "restriction","revenue","rhetoric","rhythm","ritual","rivalry","rod",
    "romance","rural","sanction","sanctuary","scandal","scenario",
    "scholarship","scope","sculpture","sector","segment","seizure",
    "semester","seminar","sensation","sentiment","sequence","settlement",
    "shaft","significance","simulation","sir","sketch","slot","slogan",
    "slope","solidarity","specification","specimen","spectrum",
    "speculation","sphere","spine","spokesman","spouse","stake","stance",
    "statute","stimulus","strand","streak","strip","stroke","suburb",
    "succession","suite","summit","supplement","surplus","surveillance",
    "suspension","swamp","syndrome","syntax","target","tactic",
    "telecommunications","tenant","tendency","tension","terminal",
    "territory","testimony","texture","therapy","thesis","threshold",
    "timber","tissue","tobacco","toll","trademark","tragedy","trait",
    "transaction","transition","transmission","tribunal","tribute","troop",
    "trunk","tunnel","turnover","tutor","twist","utility","vegetation",
    "venture","verdict","vessel","veteran","virtue","visa","vision",
    "vocabulary","volcano","warrant","warrior","welfare","wilderness",
    "workforce","workshop","zone",
    # 形容词 / 副词（高中 / CET-4 提升）
    "abstract","abundant","accurate","acute","adequate","adjacent",
    "aesthetic","aggressive","alike","alleged","alternate","amateur",
    "ambitious","ample","anonymous","applicable","arbitrary","authentic",
    "automatic","bare","beneficial","bold","chronic","civic","cognitive",
    "coherent","collective","colonial","comparable","compelling",
    "competent","comprehensive","compulsory","concrete","consecutive",
    "contemporary","controversial","conventional","core","corporate",
    "corresponding","decent","dedicated","deliberate","delicate",
    "dense","dependable","diagnostic","digital","discrete","distinct",
    "diverse","domestic","dominant","dramatic","dynamic","elaborate",
    "elegant","eligible","empirical","enormous","equivalent","eternal",
    "ethical","evident","exceptional","excessive","exclusive","exotic",
    "explicit","extraordinary","fatal","favorable","feasible","flexible",
    "formal","formidable","fragile","fundamental","generous","genetic",
    "genuine","geographical","gradual","graphic","gross","handy",
    "harsh","hostile","humble","identical","ignorant","illegal","immense",
    "immune","implicit","impressive","inadequate","inevitable","infinite",
    "informal","inherent","initial","innocent","innovative","intact",
    "intense","intermediate","intimate","intriguing","intuitive","invalid",
    "invisible","isolated","keen","legitimate","liable","liberal","literal",
    "logical","magnificent","mandatory","marginal","massive","medieval",
    "mere","mild","minimal","mobile","moderate","modest","moral",
    "municipal","mutual","naked","neat","neutral","noble","notable",
    "notorious","novel","nuclear","numerous","objective","obscure",
    "ongoing","optical","optimal","organic","outstanding","overwhelming",
    "partial","passive","peculiar","permanent","persistent","philosophical",
    "portable","potential","practical","preliminary","premier","premium",
    "prevalent","primitive","principal","productive","profound",
    "progressive","prominent","prone","prospective","provisional",
    "radical","random","rational","realistic","rear","reasonable",
    "redundant","relevant","reluctant","remarkable","remote","renowned",
    "respective","rigid","robust","romantic","rural","sacred","scare",
    "secular","selective","simultaneous","skeptical","slim","sole",
    "sophisticated","sovereign","spare","spectacular","spontaneous",
    "stable","stiff","straightforward","strategic","substantial",
    "subtle","successive","sufficient","superficial","superior",
    "supplementary","supreme","sustainable","symbolic","sympathetic",
    "synthetic","systematic","tactical","temporary","tender","tentative",
    "terminal","terrestrial","toxic","transparent","tremendous","tribal",
    "trivial","tropical","turbulent","ultimate","uncertain","underlying",
    "undergraduate","undoubtedly","uniform","universal","unprecedented",
    "urban","urgent","vacant","vague","valid","variable","verbal",
    "vertical","viable","virtual","vivid","vocal","voluntary","vulnerable",
    "wholesale","widespread",
    "accordingly","adequately","allegedly","alternatively","approximately",
    "automatically","broadly","chronically","collectively","commonly",
    "comparatively","consistently","continuously","conversely",
    "correspondingly","deliberately","desperately","dramatically",
    "efficiently","enormously","exclusively","explicitly","extensively",
    "formally","formerly","fundamentally","genuinely","globally",
    "hence","hopefully","ideally","implicitly","importantly",
    "increasingly","independently","inevitably","initially","intensely",
    "jointly","literally","meanwhile","merely","moreover","namely",
    "nevertheless","nonetheless","notably","occasionally","officially",
    "otherwise","overall","partly","permanently","presumably",
    "progressively","promptly","respectively","roughly","seemingly",
    "selectively","separately","severely","simultaneously","solely",
    "subsequently","substantially","supposedly","thereby","thus",
    "traditionally","virtually","whereby","wherever",
}

_COLLEGE = {
    # 动词（CET-6 / 大学提升）
    "abstain","accelerate","accommodate","adhere","affiliate","aggravate",
    "alienate","alleviate","allot","amend","amplify","annex","annotate",
    "appease","apprehend","arbitrate","articulate","ascertain","aspire",
    "attest","augment","authenticate","avail","avert","bestow","breach",
    "buffer","calibrate","capitalize","cater","centralize","certify",
    "chronicle","circumvent","coerce","coincide","commemorate","commute",
    "compartmentalize","compel","complement","comply","comprehend",
    "conceive","concede","condense","confiscate","conform","congregate",
    "conjecture","consolidate","constrain","contemplate","contend",
    "contradict","converge","convey","corrode","counterfeit","culminate",
    "curtail","cushion","deem","default","defer","delegate","demolish",
    "deploy","deprive","designate","deter","detain","deteriorate",
    "deviate","differentiate","diffuse","dilute","discard","discern",
    "disclose","discontinue","discredit","disdain","dismantle","disperse",
    "displace","disseminate","dissolve","divert","divulge","domesticate",
    "downplay","duplicate","dwarf","dwell","elicit","embark","embed",
    "embody","enact","encompass","endorse","engrave","enlighten","enrich",
    "ensue","entail","entrust","envision","eradicate","erode","escalate",
    "evacuate","exaggerate","exert","exempt","exhaust","exile","expedite",
    "expel","exploit","extinguish","fabricate","facilitate","falsify",
    "fatigue","flaw","fluctuate","forge","formulate","foster","fragment",
    "gaze","grapple","hamper","harass","harness","hasten","hinder","hoist",
    "illuminate","immerse","impair","impeach","impede","implicate",
    "inaugurate","incite","incorporate","incur","induce","infiltrate",
    "inflict","inhibit","initiate","innovate","inoculate","inscribe",
    "instigate","institutionalize","intensify","intercept","interrogate",
    "intervene","intimidate","invoke","jeopardize","juxtapose","kindle",
    "lavish","levy","linger","liquidate","litigate","loom","lure",
    "magnify","manifest","manipulate","marginalize","mediate","merge",
    "mobilize","modulate","monopolize","negate","neutralize","nourish",
    "nurture","obliterate","obscure","obstruct","offset","optimize",
    "orchestrate","outweigh","oversee","overhaul","overthrow","penetrate",
    "perpetuate","permeate","pertain","petition","pinpoint","plagiarize",
    "polarize","postulate","preclude","preempt","presume","prevail",
    "proclaim","procure","proliferate","propagate","prosecute","provoke",
    "purge","quantify","quench","ratify","rationalize","rebuke","recede",
    "reconcile","rectify","redeem","refine","refrain","refute","reimburse",
    "reiterate","relinquish","render","repeal","replenish","replicate",
    "repudiate","resemble","resent","reside","retaliate","retrieve",
    "retrospect","revamp","revert","revoke","revolve","ridicule","rupture",
    "safeguard","saturate","scrutinize","segregate","sideline","signify",
    "slaughter","smuggle","solicit","speculate","stagger","standardize",
    "stipulate","streamline","subsidize","subvert","suffice","superimpose",
    "supervise","supplant","supplement","suppress","surmount","surrender",
    "suspend","synthesize","tamper","terminate","testify","topple",
    "transcend","transgress","transplant","traverse","trivialize",
    "underestimate","undermine","underscore","unify","unravel","uphold",
    "usurp","validate","venture","vindicate","violate","warrant","withhold",
    "withstand","wreck",
    # 名词（CET-6 / 大学提升）
    "abstraction","accountability","adjective","advent","adversary",
    "affiliation","aftermath","allegation","allegiance","alloy","ambiguity",
    "amnesty","analogy","anatomy","anecdote","anomaly","anthem","apparatus",
    "appendix","appraisal","apprentice","aptitude","archipelago","artifact",
    "assertion","asset","asymmetry","atrocity","austerity","autonomy",
    "backlash","ballot","bandwidth","baseline","benchmark","beneficiary",
    "biography","blueprint","boulevard","bounty","bureaucracy","caliber",
    "canopy","capita","carousel","catalyst","caveat","censorship",
    "chromosome","chronicle","clout","coalition","coexistence","collateral",
    "combustion","commemoration","commodity","communism","compatriot",
    "compilation","compliance","complication","compromise","concession",
    "condolence","confederation","confrontation","conglomerate",
    "congregation","connotation","consolidation","constellation",
    "constituency","contingency","continuum","contraband","conveyance",
    "copyright","correlation","counterpart","credentials","creed",
    "culmination","debris","decentralization","deficit","deficiency",
    "deliberation","demographic","denomination","deterrent","dictatorship",
    "dilemma","diplomacy","discrepancy","disposition","dissent",
    "dissertation","dividend","doctrine","embargo","empowerment",
    "encryption","endeavor","endorsement","enterprise","entrepreneur",
    "enumeration","equilibrium","equity","erosion","espionage",
    "ethnicity","excerpt","exemption","exodus","expenditure","extradition",
    "faction","fallacy","famine","fatality","feud","fiasco","fidelity",
    "flagship","flaw","folklore","forerunner","forfeit","fossil",
    "franchise","garrison","genocide","genre","grievance","guerrilla",
    "hallmark","havoc","hegemony","hemisphere","heritage","hierarchy",
    "homicide","hurdle","hypocrisy","ideology","immunity","impeachment",
    "impetus","incentive","incidence","inclusion","incumbent","indictment",
    "infrastructure","injunction","insolvency","insurgency","integrity",
    "interface","intermediary","intricacy","intuition","irony","itinerary",
    "jargon","jurisdiction","kinship","labyrinth","landmark","latitude",
    "legislation","leverage","liaison","litigation","loophole","magnitude",
    "malice","mandate","manifesto","manuscript","maritime","memoir",
    "metaphor","methodology","militia","misconception","momentum",
    "monopoly","moratorium","mortality","mosaic","municipality","nemesis",
    "nomenclature","nostalgia","nuance","obituary","oligarchy","omission",
    "onset","ordinance","oversight","paradigm","paradox","parameter",
    "parity","pedagogy","peer","penchant","philanthropy","pinnacle",
    "plagiarism","plateau","plausibility","plurality","polarization",
    "posterity","pragmatism","precedent","precinct","predicament",
    "preemption","premise","prerogative","prevalence","procurement",
    "prodigy","prognosis","prohibition","proliferation","propaganda",
    "proprietor","protagonist","provenance","proxy","pseudonym","quarantine",
    "quorum","ramification","rapport","rationale","rebate","receptacle",
    "reconnaissance","redemption","referendum","regime","registry",
    "rehabilitation","remittance","renaissance","repertoire","repercussion",
    "repository","reprieve","requisite","residue","resilience","respite",
    "resurgence","retribution","revelation","rhetoric","rigidity",
    "sabotage","sanctuary","satire","scaffold","scrutiny","semblance",
    "severance","skepticism","solidarity","sovereignty","stalemate",
    "stereotype","stigma","stipulation","stratification","subsidy",
    "substrate","supremacy","surplus","sustenance","symbiosis","symposium",
    "synopsis","tariff","taxonomy","tenure","trajectory","transcript",
    "transparency","trauma","tribunal","ultimatum","vanguard","versatility",
    "veto","viability","vocation","volatility","watershed",
}

_IELTS = {
    # 动词（雅思 / 高级学术）
    "abate","abjure","abnegate","abrogate","absolve","acclimatize",
    "accolade","accrue","adjudicate","admonish","adulterate","aggrandize",
    "amalgamate","ameliorate","annihilate","anoint","append","appraise",
    "appropriate","arraign","assimilate","attenuate","beguile","belittle",
    "bequeath","bereave","bifurcate","bolster","brandish","buttress",
    "cajole","capitulate","castigate","catalyze","circumscribe",
    "clamor","coalesce","codify","cogitate","collate","commiserate",
    "conflate","consecrate","corroborate","countermand","debilitate",
    "decimate","decommission","delineate","demarcate","demystify",
    "denigrate","deplete","deprecate","deregulate","desecrate","dissipate",
    "distill","divest","edify","effectuate","emanate","emancipate",
    "embellish","emulate","engender","enshrine","enumerate","epitomize",
    "equivocate","espouse","exacerbate","exalt","excoriate","exonerate",
    "expatriate","extol","extrapolate","fathom","felicitate","ferment",
    "flout","foreclose","forestall","galvanize","garner","germinate",
    "gerrymander","goad","gyrate","homogenize","hypothesize","imbue",
    "immolate","impound","improvise","incapacitate","incinerate",
    "inculcate","indemnify","infer","ingratiate","insinuate","interpolate",
    "inundate","invigorate","iterate","lambaste","languish","levitate",
    "liquefy","locomote","mandate","mastermind","matriculate","meditate",
    "mitigate","mollify","morph","muster","nationalize","navigate",
    "necessitate","nominate","nullify","obfuscate","obliterate","obviate",
    "ostracize","overrule","pacify","palliate","partition","patronize",
    "penalize","percolate","perpetrate","perturb","placate","pontificate",
    "precipitate","predispose","presuppose","privatize","procrast" + "inate",
    "prognosticate","promulgate","propitiate","proscribe","proxy",
    "rationalize","recapitulate","reciprocate","recount","redress",
    "reformulate","relegate","remand","remonstrate","renounce","reprimand",
    "requite","rescind","resuscitate","retrograde","ritualize","ruminate",
    "sanction","sanitize","satiate","scapegoat","sequester","shortlist",
    "stagnate","stigmatize","subjugate","sublimate","subordinate",
    "subsidize","substantiate","supplicate","surmise","synergize",
    "tabulate","tantalize","temporize","transfigure","transgress",
    "triangulate","underscore","undulate","usher","vacillate","valorize",
    "venerate","vilify","vindicate","vitiate","vociferate",
    # 名词（雅思 / 高级学术）
    "aberration","abstinence","accolade","acumen","adjunct","admonition",
    "aegis","affidavit","affirmation","affluence","alcove","altruism",
    "amalgamation","ambivalence","anachronism","anathema","antecedent",
    "antipathy","antithesis","apathy","aphorism","apotheosis","appellation",
    "archetype","ascendancy","attrition","avarice","axiom","bastion",
    "bedrock","behemoth","bellwether","benediction","benevolence","bigotry",
    "boondoggle","bourgeoisie","brinkmanship","cacophony","capitulation",
    "caricature","carte","catharsis","caucus","chasm","chimera","clairvoyance",
    "cliche","cognition","colloquium","commencement","compendium",
    "complacency","conceit","concordance","conduit","conflagration",
    "connoisseur","consortium","contrition","conundrum","cordon",
    "corollary","crux","dearth","debacle","decadence","deference",
    "demagogue","denouement","dereliction","diatribe","dichotomy",
    "dissonance","dystopia","echelon","efficacy","egalitarianism",
    "elixir","eloquence","emissary","empathy","enclave","enigma",
    "ennui","epiphany","epitome","equanimity","escapade","ethos",
    "euphemism","exigency","expediency","extravagance","facade","facet",
    "facsimile","fallout","fervor","firebrand","flux","foray","foreboding",
    "fortitude","fracas","fulcrum","gambit","genesis","geopolitics",
    "grandeur","gravitas","guise","harbinger","heyday","hubris",
    "iconoclast","idiosyncrasy","impasse","impunity","inauspicious",
    "incantation","incongruity","indignation","inertia","infidelity",
    "influx","innuendo","insolvency","intransigence","invective",
    "juggernaut","juxtaposition","largesse","lectern","leniency",
    "lethargy","lexicon","lineage","litany","machination","magnanimity",
    "malaise","malfeasance","manifold","maxim","melee","meritocracy",
    "microcosm","milieu","minutiae","misnomer","morass","myriad",
    "nadir","negligence","nihilism","nomenclature","nonchalance",
    "novice","oasis","oblivion","omnipotence","onus","opulence",
    "orthodoxy","overture","palate","panacea","panache","panoply",
    "pariah","parlance","pastiche","pathos","patrimony","pedagogy",
    "pedant","penumbra","perquisite","perspicacity","philistine",
    "platitude","plethora","polemic","pragmatist","precursor","predilection",
    "preeminence","premonition","preponderance","prerequisite","pretense",
    "primacy","proletariat","promontory","propensity","prophesy",
    "propriety","proselytism","proviso","proximity","purview","putsch",
    "quagmire","quandary","quintessence","raison","rapprochement",
    "recalcitrance","recluse","reconstitution","rectitude","redux",
    "remuneration","rendition","renunciation","repertory","repose",
    "reprisal","requisition","resonance","restitution","resurgence",
    "reverence","sacrilege","sagacity","salient","salvo","scion",
    "sediment","serfdom","soliloquy","solstice","sophistry","stalemate",
    "subterfuge","subtlety","supposition","surfeit","synergy","tableau",
    "temerity","tenacity","testament","travesty","treatise","truism",
    "tumult","turpitude","ubiquity","ultimatum","umbrage","underpinning",
    "unilateralism","utopia","vagary","vanguard","vehemence","vendetta",
    "veracity","vestige","vicissitude","vignette","virtuosity","vista",
    "volition","zeitgeist",
}

_PROFESSIONAL = {
    # 动词（专业/极高级，只出现在学术论文/行业报告）
    "abnegate","ablate","absquatulate","accrete","adjure","adsorb",
    "aerosolize","agglomerate","anastomose","anodize","apportion",
    "arrogate","assay","attrit","bioaccumulate","calcify","cannulate",
    "catheterize","chelate","circumnavigate","coapt","conflate",
    "cryopreserve","deconvolve","defibrillate","degas","delimit",
    "demineralize","denature","derepress","desalinate","dimerize",
    "disaggregate","edulcorate","electrophorese","elucidate","emulsify",
    "epoxidize","equilibrate","esterify","exfoliate","fractionate",
    "gasify","gelatinize","granulate","hemolyze","homologate",
    "hydrolyze","hypertrophy","hypothecate","immunize","incubate",
    "intubate","ionize","irradiate","isomerize","lyophilize","methylate",
    "microdose","nebulize","nucleate","ossify","oxidize","pasteurize",
    "phosphorylate","photosensitize","plasticize","polymerize","potentiate",
    "precipitate","pressurize","proliferate","pyrolyze","recrystallize",
    "remineralize","resect","retort","saponify","sinter","solubilize",
    "sonicate","sterilize","sublimate","sulfonate","tare","titrate",
    "transduce","ultracentrifuge","vaporize","vitrify","volatilize",
    # 名词（专业/极高级）
    "ablation","absorbance","accretion","acetylcholine","acoustics",
    "adenosine","adiposity","adsorption","aetiology","agglomeration",
    "allosteric","amortization","anaphylaxis","angiogenesis","anisotropy",
    "antigen","apoptosis","arrhythmia","arteriosclerosis","assay",
    "atelectasis","bioavailability","bioinformatics","biosynthesis",
    "brachytherapy","carcinogenesis","chemotaxis","chromatography",
    "cladistics","coagulation","comorbidity","cytokine","deconvolution",
    "denaturation","desalination","diagenesis","diapedesis","dimorphism",
    "dislocation","dosimetry","elasticity","electrolysis","embolism",
    "endocytosis","enthalpy","entropy","epidemiology","epigenetics",
    "etiology","exocytosis","fibrillation","fluorescence","genotype",
    "glycolysis","half-life","hematocrit","hemodynamics","hemostasis",
    "histology","homeostasis","hydrolysis","hypoxia","immunoassay",
    "impedance","inflammasome","isotope","kinase","kinetics","lipolysis",
    "luminescence","lysis","macrophage","mesothelioma","metabolite",
    "metastasis","microbiome","mitochondria","morphology","necrosis",
    "neuropathy","oncogene","osmosis","osteoclast","oxidation","pathogen",
    "pathophysiology","peptide","pharmacokinetics","phenotype","photon",
    "phylogeny","piezoelectricity","plasmon","polymorphism","prion",
    "proteomics","radionuclide","reagent","refractive","restenosis",
    "rheology","ribosome","sedimentation","sepsis","serology","spectrometry",
    "sterilization","stoichiometry","supernatant","susceptibility",
    "synapse","teratogen","thermodynamics","thrombosis","tomography",
    "toxicology","transcriptome","transduction","turbulence","vasculature",
    "viscosity","voltammetry","xenobiotic","zymogen",
}

# ──────────────────────────────────────────────
# 每级的增量词集
# ──────────────────────────────────────────────
_LEVEL_INCREMENTS: dict[str, set[str]] = {
    "kindergarten":  _KINDERGARTEN,
    "elementary":    _ELEMENTARY,
    "middle_school": _MIDDLE_SCHOOL,
    "high_school":   _HIGH_SCHOOL,
    "college":       _COLLEGE,
    "ielts":         _IELTS,
    "professional":  _PROFESSIONAL,
}


@lru_cache(maxsize=len(LEVEL_ORDER))
def get_known_words(level: str) -> frozenset[str]:
    """返回该等级及以下所有词汇的合集（用于过滤已知词）"""
    if level not in _LEVEL_INCREMENTS:
        level = "high_school"  # 默认

    words: set[str] = set()
    for lvl in LEVEL_ORDER:
        words |= _LEVEL_INCREMENTS[lvl]
        if lvl == level:
            break
    return frozenset(words)


# 向后兼容：保留 COMMON_WORDS 供其他模块使用（等同 high_school 级别）
COMMON_WORDS = get_known_words("high_school")


def get_level_info() -> list[dict]:
    """返回所有等级信息，供前端展示"""
    result = []
    cumulative = 0
    for lvl in LEVEL_ORDER:
        cumulative += len(_LEVEL_INCREMENTS[lvl])
        result.append({
            "key": lvl,
            "label": LEVEL_LABELS[lvl],
            "word_count": cumulative,
        })
    return result
